//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Activity : BaseClass
    {
        public Activity()
        {
            this.Entity = new HashSet<Entity>();
    		
            this.EntityField = new HashSet<EntityField>();
    		
            this.UserRoleActivity = new HashSet<UserRoleActivity>();
    		
        }
    
        // Primitive properties
    
    	
    	public int ActivityID { get; set; }
    	
    	public int StpActivityGroupID { get; set; }
    	
    	public string ActivityName { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    	    
    	
    		public ICollection<Entity> Entity { get; set; }
    	
    	    
    	
    		public ICollection<EntityField> EntityField { get; set; }
    	
    	    
    	
    		public ICollection<UserRoleActivity> UserRoleActivity { get; set; }
    	
    	}
}
