//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Application : BaseClass
    {
        public Application()
        {
            this.Page = new HashSet<Page>();
    		
        }
    
        // Primitive properties
    
    	
    	public int ApplicationID { get; set; }
    	
    	public string ApplicationName { get; set; }
    	
    	public Nullable<int> StpApplicationType { get; set; }
    	
    	public string StpApplicationFrameworkID { get; set; }
    	
    	public string Logo { get; set; }
    	
    	public Nullable<bool> IsTrial { get; set; }
    	
    	public Nullable<System.DateTime> LastBuildDate { get; set; }
    	
    	public Nullable<int> CompanyID { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    	    
    	
    		public ICollection<Page> Page { get; set; }
    	
    	}
}
