//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Audit : BaseClass
    {
        // Primitive properties
    
    	
    	public int AuditID { get; set; }
    	
    	public Nullable<int> UserID { get; set; }
    	
    	public Nullable<System.DateTime> DateTime { get; set; }
    	
    	public string TableName { get; set; }
    	
    	public string FieldName { get; set; }
    	
    	public string OldFieldValue { get; set; }
    	
    	public string NewFieldValue { get; set; }
    	
    	public bool IsCustomField { get; set; }
    	
    	public int StpUserActionID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    	}
}
