//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Consumable : BaseClass
    {
        // Primitive properties
    
    	
    	public int ConsumableID { get; set; }
    	
    	public Nullable<int> StpConsumableTypeID { get; set; }
    	
    	public Nullable<int> StpUnitOfMeasureID { get; set; }
    	
    	public Nullable<int> AssetID { get; set; }
    	
    	public Nullable<decimal> QuantityInUOM { get; set; }
    	
    	public Nullable<int> StpUOMForOpenAndCloseID { get; set; }
    	
    	public Nullable<decimal> OpeningQuantity { get; set; }
    	
    	public Nullable<decimal> ClosingQuantity { get; set; }
    	
    	public string Reason { get; set; }
    	
    	public Nullable<int> UsedOnAssetID { get; set; }
    	
    	public string Supplier { get; set; }
    	
    	public Nullable<decimal> PurchasePrice { get; set; }
    	
    	public Nullable<System.DateTime> PurchaseDate { get; set; }
    	
    	public Nullable<decimal> PurchaseTax { get; set; }
    	
    	public Nullable<decimal> PurchaseCosts { get; set; }
    	
    	public bool IsPurchase { get; set; }
    	
    	public bool IsClaimable { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    	
    	public Nullable<int> ChangedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Asset Asset { get; set; }
    	
    		
    		
        
    		public Asset Asset1 { get; set; }
    	
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public StpData StpData1 { get; set; }
    	
    		
    		
        
    		public StpData StpData2 { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    		
    		
        
    		public User User1 { get; set; }
    	
    	}
}
