//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Contact : BaseClass
    {
        public Contact()
        {
            this.User = new HashSet<User>();
    		
        }
    
        // Primitive properties
    
    	
    	public int ContactID { get; set; }
    	
    	public Nullable<int> StpContactTypeID { get; set; }
    	
    	public Nullable<int> StpLanguageID { get; set; }
    	
    	public Nullable<int> StpTitleID { get; set; }
    	
    	public Nullable<int> StpIdentityTypeID { get; set; }
    	
    	public string Initials { get; set; }
    	
    	public string FirstName { get; set; }
    	
    	public string MiddleName { get; set; }
    	
    	public string LastName { get; set; }
    	
    	public string FullName { get; set; }
    	
    	public string Email { get; set; }
    	
    	public Nullable<int> StpPreferredCorresspondenceMethodID { get; set; }
    	
    	public Nullable<int> StpPreferredContactMethodID { get; set; }
    	
    	public string IdentityNo { get; set; }
    	
    	public string StaffNo { get; set; }
    	
    	public Nullable<System.DateTime> DateOfBirth { get; set; }
    	
    	public string Gender { get; set; }
    	
    	public bool IsPerson { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public StpData StpData1 { get; set; }
    	
    		
    		
        
    		public StpData StpData2 { get; set; }
    	
    		
    		
        
    		public StpData StpData3 { get; set; }
    	
    		
    		
        
    		public StpData StpData4 { get; set; }
    	
    		
    		
        
    		public StpData StpData5 { get; set; }
    	
    	    
    	
    		public ICollection<User> User { get; set; }
    	
    	}
}
