//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Document : BaseClass
    {
        // Primitive properties
    
    	
    	public int DocumentID { get; set; }
    	
    	public string DocumentName { get; set; }
    	
    	public string Path { get; set; }
    
    }
}
