//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class EntityField : BaseClass
    {
        public EntityField()
        {
            this.EntityField1 = new HashSet<EntityField>();
    		
            this.EntityFieldValue = new HashSet<EntityFieldValue>();
    		
        }
    
        // Primitive properties
    
    	
    	public int EntityFieldID { get; set; }
    	
    	public int EntityID { get; set; }
    	
    	public Nullable<int> EntityFieldDataTypeID { get; set; }
    	
    	public Nullable<int> ActivityID { get; set; }
    	
    	public Nullable<int> StcControlTypeID { get; set; }
    	
    	public string EntityFieldName { get; set; }
    	
    	public string DisplayName { get; set; }
    	
    	public string GroupBoxName { get; set; }
    	
    	public Nullable<int> GroupBoxOrder { get; set; }
    	
    	public string GroupBoxWidth { get; set; }
    	
    	public string TabName { get; set; }
    	
    	public Nullable<int> TabOrderNo { get; set; }
    	
    	public Nullable<int> ComboBoxDisplayFieldID { get; set; }
    	
    	public string RegularExpression { get; set; }
    	
    	public bool IsCustomField { get; set; }
    	
    	public bool IsInGridDisplay { get; set; }
    	
    	public bool AddBoxSpinners { get; set; }
    	
    	public string ComboBoxDefaultText { get; set; }
    	
    	public string CalendarMaxValue { get; set; }
    	
    	public string CalendarMinValue { get; set; }
    	
    	public string UploadFileSaveToPath { get; set; }
    	
    	public string ScriptInsert { get; set; }
    	
    	public bool IsMandatory { get; set; }
    	
    	public bool IsPrimaryKey { get; set; }
    	
    	public bool IsForeignKey { get; set; }
    	
    	public string ForeignTable { get; set; }
    	
    	public string FilterBy { get; set; }
    	
    	public bool IsHidden { get; set; }
    	
    	public bool IsToolTip { get; set; }
    	
    	public bool IsDisabled { get; set; }
    	
    	public Nullable<int> Max { get; set; }
    	
    	public int Min { get; set; }
    	
    	public string ControlLength { get; set; }
    	
    	public string ControlHeight { get; set; }
    	
    	public Nullable<int> ControlOrderNo { get; set; }
    	
    	public string ControlScreenColumns { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Activity Activity { get; set; }
    	
    		
    		
        
    		public Entity Entity { get; set; }
    	
    	    
    	
    		public ICollection<EntityField> EntityField1 { get; set; }
    	
    		
    		
        
    		public EntityField EntityField2 { get; set; }
    	
    		
    		
        
    		public EntityField EntityField11 { get; set; }
    	
    		
    		
        
    		public EntityField EntityField3 { get; set; }
    	
    		
    		
        
    		public EntityFieldDataType EntityFieldDataType { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    	    
    	
    		public ICollection<EntityFieldValue> EntityFieldValue { get; set; }
    	
    	}
}
