//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class EntityResource : BaseClass
    {
        // Primitive properties
    
    	
    	public int ResourceID { get; set; }
    	
    	public string ResourceKey { get; set; }
    	
    	public string ResourceValue { get; set; }
    	
    	public string ResourceCulture { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    	}
}
