//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class EntityFieldDataType : BaseClass
    {
        public EntityFieldDataType()
        {
            this.EntityField = new HashSet<EntityField>();
    		
        }
    
        // Primitive properties
    
    	
    	public int EntityFieldDataTypeID { get; set; }
    	
    	public string Type { get; set; }
    
    		// Navigation properties
    
    	    
    	
    		public ICollection<EntityField> EntityField { get; set; }
    	
    	}
}
