//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Entity : BaseClass
    {
        public Entity()
        {
            this.EntityField = new HashSet<EntityField>();
    		
            this.EntityValues = new HashSet<EntityValues>();
    		
            this.Page = new HashSet<Page>();
    		
        }
    
        // Primitive properties
    
    	
    	public int EntityID { get; set; }
    	
    	public Nullable<int> ActivityID { get; set; }
    	
    	public string Name { get; set; }
    	
    	public string TableName { get; set; }
    	
    	public bool IsMultiLanguage { get; set; }
    	
    	public bool IsTabbedForm { get; set; }
    	
    	public bool IsMultiGrid { get; set; }
    	
    	public int MaxNoFieldsInGrpBox { get; set; }
    	
    	public string MngCtlrName { get; set; }
    	
    	public string PathSetupForm { get; set; }
    	
    	public string PathEditTemplate { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Activity Activity { get; set; }
    	
    		
    		
        
    		public Organization Organization { get; set; }
    	
    	    
    	
    		public ICollection<EntityField> EntityField { get; set; }
    	
    	    
    	
    		public ICollection<EntityValues> EntityValues { get; set; }
    	
    	    
    	
    		public ICollection<Page> Page { get; set; }
    	
    	}
}
