//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class EntityFieldValue : BaseClass
    {
        // Primitive properties
    
    	
    	public int EntityFieldValueID { get; set; }
    	
    	public int EntityFieldID { get; set; }
    	
    	public int StpLanguageID { get; set; }
    	
    	public int UniqueRowID { get; set; }
    	
    	public string TextFieldValue { get; set; }
    	
    	public Nullable<bool> BitFieldValue { get; set; }
    	
    	public Nullable<decimal> DecimalFieldValue { get; set; }
    	
    	public Nullable<int> IntegerFieldValue { get; set; }
    	
    	public Nullable<System.DateTime> DateTimeFieldValue { get; set; }
    	
    	public Nullable<System.DateTime> SmallDateTimeFieldValue { get; set; }
    	
    	public byte[] ImageFieldName { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public EntityField EntityField { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    	}
}
