//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class EntityValues : BaseClass
    {
        // Primitive properties
    
    	
    	public int EntityID { get; set; }
    	
    	public int UDC_ValuesID { get; set; }
    	
    	public int UniqueRowID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Entity Entity { get; set; }
    	
    	}
}
