//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Forum : BaseClass
    {
        // Primitive properties
    
    	
    	public int ForumID { get; set; }
    	
    	public int StpForumCategoryID { get; set; }
    	
    	public int DiscussionIdentity { get; set; }
    	
    	public string DiscussionTitle { get; set; }
    	
    	public string Message { get; set; }
    	
    	public string Filename { get; set; }
    	
    	public byte[] FileData { get; set; }
    	
    	public string ContentType { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    	
    	public Nullable<int> ChangedByID { get; set; }
    
    }
}
