//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class HitecJob : BaseClass
    {
        // Primitive properties
    
    	
    	public int HitecJobID { get; set; }
    	
    	public string Fullname { get; set; }
    	
    	public string Email { get; set; }
    	
    	public Nullable<int> StpHitecClientID { get; set; }
    	
    	public string Client { get; set; }
    	
    	public string ContactNumber { get; set; }
    	
    	public Nullable<int> StpCityID { get; set; }
    	
    	public string PhysicalAddressGuardPost { get; set; }
    	
    	public string BillingAddress { get; set; }
    	
    	public int NumberOfGuardsDaytime { get; set; }
    	
    	public int NumberOfGuardsNighttime { get; set; }
    	
    	public Nullable<System.DateTimeOffset> StartDate { get; set; }
    	
    	public Nullable<System.TimeSpan> StartTime { get; set; }
    	
    	public Nullable<System.DateTimeOffset> EndDate { get; set; }
    	
    	public Nullable<System.TimeSpan> EndTime { get; set; }
    	
    	public string OrderNumber { get; set; }
    	
    	public string Total { get; set; }
    	
    	public Nullable<System.DateTimeOffset> InvoicedDate { get; set; }
    	
    	public string InvoiceNo { get; set; }
    	
    	public string InvoiceComment { get; set; }
    	
    	public string Comment { get; set; }
    	
    	public bool IsInvoiced { get; set; }
    	
    	public bool IsComplete { get; set; }
    	
    	public bool IsJobCardSend { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    	
    	public Nullable<int> ChangedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    		
    		
        
    		public User User1 { get; set; }
    	
    	}
}
