//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Message : BaseClass
    {
        public Message()
        {
            this.MessageUser = new HashSet<MessageUser>();
    		
        }
    
        // Primitive properties
    
    	
    	public int MessageID { get; set; }
    	
    	public string MessageText { get; set; }
    	
    	public string Filename { get; set; }
    	
    	public byte[] FileData { get; set; }
    	
    	public string ContentType { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    	
    	public Nullable<int> ChangedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    		
    		
        
    		public User User1 { get; set; }
    	
    	    
    	
    		public ICollection<MessageUser> MessageUser { get; set; }
    	
    	}
}
