//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class MessageUser : BaseClass
    {
        // Primitive properties
    
    	
    	public int MessageUserID { get; set; }
    	
    	public string ChatName { get; set; }
    	
    	public Nullable<int> UserID { get; set; }
    	
    	public Nullable<int> MessageID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Message Message { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    	}
}
