//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class NotificationLevel : BaseClass
    {
        public NotificationLevel()
        {
            this.UserRoleNotificationLevel = new HashSet<UserRoleNotificationLevel>();
    		
        }
    
        // Primitive properties
    
    	
    	public int NotificationLevelID { get; set; }
    	
    	public string Description { get; set; }
    	
    	public bool Report { get; set; }
    	
    	public bool Sms { get; set; }
    	
    	public bool Email { get; set; }
    	
    	public bool CaseEscalation { get; set; }
    
    		// Navigation properties
    
    	    
    	
    		public ICollection<UserRoleNotificationLevel> UserRoleNotificationLevel { get; set; }
    	
    	}
}
