//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Organization : BaseClass
    {
        public Organization()
        {
            this.Activity = new HashSet<Activity>();
    		
            this.Application = new HashSet<Application>();
    		
            this.Asset = new HashSet<Asset>();
    		
            this.Audit = new HashSet<Audit>();
    		
            this.Consumable = new HashSet<Consumable>();
    		
            this.Contact = new HashSet<Contact>();
    		
            this.Document = new HashSet<Document>();
    		
            this.Entity = new HashSet<Entity>();
    		
            this.EntityResource = new HashSet<EntityResource>();
    		
            this.Message = new HashSet<Message>();
    		
            this.Person = new HashSet<Person>();
    		
            this.Product = new HashSet<Product>();
    		
            this.Production = new HashSet<Production>();
    		
            this.StcData = new HashSet<StcData>();
    		
            this.StcDataType = new HashSet<StcDataType>();
    		
            this.StpData = new HashSet<StpData>();
    		
            this.StpDataType = new HashSet<StpDataType>();
    		
            this.Supplier = new HashSet<Supplier>();
    		
            this.User1 = new HashSet<User>();
    		
        }
    
        // Primitive properties
    
    	
    	public string OrganizationName { get; set; }
    	
    	public string Description { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    	    
    	
    		public ICollection<Activity> Activity { get; set; }
    	
    	    
    	
    		public ICollection<Application> Application { get; set; }
    	
    	    
    	
    		public ICollection<Asset> Asset { get; set; }
    	
    	    
    	
    		public ICollection<Audit> Audit { get; set; }
    	
    	    
    	
    		public ICollection<Consumable> Consumable { get; set; }
    	
    	    
    	
    		public ICollection<Contact> Contact { get; set; }
    	
    	    
    	
    		public ICollection<Document> Document { get; set; }
    	
    	    
    	
    		public ICollection<Entity> Entity { get; set; }
    	
    	    
    	
    		public ICollection<EntityResource> EntityResource { get; set; }
    	
    	    
    	
    		public ICollection<Message> Message { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person { get; set; }
    	
    	    
    	
    		public ICollection<Product> Product { get; set; }
    	
    	    
    	
    		public ICollection<Production> Production { get; set; }
    	
    	    
    	
    		public ICollection<StcData> StcData { get; set; }
    	
    	    
    	
    		public ICollection<StcDataType> StcDataType { get; set; }
    	
    	    
    	
    		public ICollection<StpData> StpData { get; set; }
    	
    	    
    	
    		public ICollection<StpDataType> StpDataType { get; set; }
    	
    	    
    	
    		public ICollection<Supplier> Supplier { get; set; }
    	
    	    
    	
    		public ICollection<User> User1 { get; set; }
    	
    	}
}
