//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Page : BaseClass
    {
        public Page()
        {
            this.EntityMenu = new HashSet<EntityMenu>();
    		
            this.Application = new HashSet<Application>();
    		
            this.Entity = new HashSet<Entity>();
    		
        }
    
        // Primitive properties
    
    	
    	public int PageID { get; set; }
    	
    	public string PageName { get; set; }
    	
    	public string IconName { get; set; }
    	
    	public string PageHeader { get; set; }
    	
    	public string PageFooter { get; set; }
    	
    	public string HtmlText { get; set; }
    	
    	public int ApplicationID { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    	    
    	
    		public ICollection<EntityMenu> EntityMenu { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    	    
    	
    		public ICollection<Application> Application { get; set; }
    	
    	    
    	
    		public ICollection<Entity> Entity { get; set; }
    	
    	}
}
