//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Part : BaseClass
    {
        public Part()
        {
            this.StockTake = new HashSet<StockTake>();
    		
            this.WorkOrderPart = new HashSet<WorkOrderPart>();
    		
        }
    
        // Primitive properties
    
    	
    	public int PartID { get; set; }
    	
    	public string Code { get; set; }
    	
    	public string Description { get; set; }
    	
    	public Nullable<int> StpPartCategoryID { get; set; }
    	
    	public string Manufacturer { get; set; }
    	
    	public string Model { get; set; }
    	
    	public string SerialNo { get; set; }
    	
    	public Nullable<int> StpUnitOfMeasureID { get; set; }
    	
    	public byte[] Barcode { get; set; }
    	
    	public byte[] PartImage { get; set; }
    	
    	public string Colour { get; set; }
    	
    	public string Size { get; set; }
    	
    	public string Style { get; set; }
    	
    	public Nullable<decimal> Price { get; set; }
    	
    	public string Supplier { get; set; }
    	
    	public Nullable<System.DateTime> WarrantyExpireDate { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public StpData StpData1 { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    	    
    	
    		public ICollection<StockTake> StockTake { get; set; }
    	
    	    
    	
    		public ICollection<WorkOrderPart> WorkOrderPart { get; set; }
    	
    	}
}
