//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Product : BaseClass
    {
        // Primitive properties
    
    	
    	public int ProductID { get; set; }
    	
    	public string Name { get; set; }
    	
    	public string Description { get; set; }
    	
    	public Nullable<decimal> Price { get; set; }
    	
    	public Nullable<int> StpCurrencyID { get; set; }
    	
    	public Nullable<int> ImageID { get; set; }
    	
    	public Nullable<int> SupplierID { get; set; }
    	
    	public string ImageName { get; set; }
    	
    	public byte[] FileData { get; set; }
    	
    	public string ContentType { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    	
    	public Nullable<int> ChangedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public Supplier Supplier { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    		
    		
        
    		public User User1 { get; set; }
    	
    	}
}
