//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class Production : BaseClass
    {
        // Primitive properties
    
    	
    	public int ProductionID { get; set; }
    	
    	public string Farm { get; set; }
    	
    	public Nullable<int> AssetID { get; set; }
    	
    	public Nullable<int> StpProductionTypeID { get; set; }
    	
    	public Nullable<int> StpFishSpeciesID { get; set; }
    	
    	public Nullable<int> StpUnitOfMeasureID { get; set; }
    	
    	public Nullable<int> Quantity { get; set; }
    	
    	public Nullable<int> UserID { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    	
    	public Nullable<int> ChangedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Asset Asset { get; set; }
    	
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public StpData StpData1 { get; set; }
    	
    		
    		
        
    		public StpData StpData2 { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    		
    		
        
    		public User User1 { get; set; }
    	
    		
    		
        
    		public User User2 { get; set; }
    	
    	}
}
