//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class StcDataType : BaseClass
    {
        public StcDataType()
        {
            this.StcData = new HashSet<StcData>();
    		
        }
    
        // Primitive properties
    
    	
    	public int StcDataTypeID { get; set; }
    	
    	public string StaticDataType { get; set; }
    	
    	public string DataSection { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    	    
    	
    		public ICollection<StcData> StcData { get; set; }
    	
    	}
}
