//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class StpData : BaseClass
    {
        public StpData()
        {
            this.Activity = new HashSet<Activity>();
    		
            this.Asset = new HashSet<Asset>();
    		
            this.Audit = new HashSet<Audit>();
    		
            this.Consumable = new HashSet<Consumable>();
    		
            this.Consumable1 = new HashSet<Consumable>();
    		
            this.Consumable2 = new HashSet<Consumable>();
    		
            this.Contact = new HashSet<Contact>();
    		
            this.Contact1 = new HashSet<Contact>();
    		
            this.Contact2 = new HashSet<Contact>();
    		
            this.Contact3 = new HashSet<Contact>();
    		
            this.Contact4 = new HashSet<Contact>();
    		
            this.Contact5 = new HashSet<Contact>();
    		
            this.Document = new HashSet<Document>();
    		
            this.EntityFieldValue = new HashSet<EntityFieldValue>();
    		
            this.Person = new HashSet<Person>();
    		
            this.Person1 = new HashSet<Person>();
    		
            this.Person2 = new HashSet<Person>();
    		
            this.Person3 = new HashSet<Person>();
    		
            this.Person4 = new HashSet<Person>();
    		
            this.Person5 = new HashSet<Person>();
    		
            this.Person6 = new HashSet<Person>();
    		
            this.Person7 = new HashSet<Person>();
    		
            this.Person8 = new HashSet<Person>();
    		
            this.Product = new HashSet<Product>();
    		
            this.Production = new HashSet<Production>();
    		
            this.Production1 = new HashSet<Production>();
    		
            this.Production2 = new HashSet<Production>();
    		
            this.User = new HashSet<User>();
    		
            this.User1 = new HashSet<User>();
    		
            this.User2 = new HashSet<User>();
    		
            this.UserRoleNotificationLevel = new HashSet<UserRoleNotificationLevel>();
    		
            this.UserRoleNotificationLevel1 = new HashSet<UserRoleNotificationLevel>();
    		
        }
    
        // Primitive properties
    
    	
    	public int StpDataID { get; set; }
    	
    	public int StpDataTypeID { get; set; }
    	
    	public string DataCode { get; set; }
    	
    	public string DataDescription { get; set; }
    	
    	public bool IsSystem { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    	    
    	
    		public ICollection<Activity> Activity { get; set; }
    	
    	    
    	
    		public ICollection<Asset> Asset { get; set; }
    	
    	    
    	
    		public ICollection<Audit> Audit { get; set; }
    	
    	    
    	
    		public ICollection<Consumable> Consumable { get; set; }
    	
    	    
    	
    		public ICollection<Consumable> Consumable1 { get; set; }
    	
    	    
    	
    		public ICollection<Consumable> Consumable2 { get; set; }
    	
    	    
    	
    		public ICollection<Contact> Contact { get; set; }
    	
    	    
    	
    		public ICollection<Contact> Contact1 { get; set; }
    	
    	    
    	
    		public ICollection<Contact> Contact2 { get; set; }
    	
    	    
    	
    		public ICollection<Contact> Contact3 { get; set; }
    	
    	    
    	
    		public ICollection<Contact> Contact4 { get; set; }
    	
    	    
    	
    		public ICollection<Contact> Contact5 { get; set; }
    	
    	    
    	
    		public ICollection<Document> Document { get; set; }
    	
    	    
    	
    		public ICollection<EntityFieldValue> EntityFieldValue { get; set; }
    	
    		
    		
        
    		public Organization Organization { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person1 { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person2 { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person3 { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person4 { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person5 { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person6 { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person7 { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person8 { get; set; }
    	
    	    
    	
    		public ICollection<Product> Product { get; set; }
    	
    	    
    	
    		public ICollection<Production> Production { get; set; }
    	
    	    
    	
    		public ICollection<Production> Production1 { get; set; }
    	
    	    
    	
    		public ICollection<Production> Production2 { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    		
    		
        
    		public StpDataType StpDataType { get; set; }
    	
    	    
    	
    		public ICollection<User> User { get; set; }
    	
    	    
    	
    		public ICollection<User> User1 { get; set; }
    	
    	    
    	
    		public ICollection<User> User2 { get; set; }
    	
    	    
    	
    		public ICollection<UserRoleNotificationLevel> UserRoleNotificationLevel { get; set; }
    	
    	    
    	
    		public ICollection<UserRoleNotificationLevel> UserRoleNotificationLevel1 { get; set; }
    	
    	}
}
