//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class StudentMeal : BaseClass
    {
        // Primitive properties
    
    	
    	public int StudentMealID { get; set; }
    	
    	public int StudentID { get; set; }
    	
    	public Nullable<int> StudentNo { get; set; }
    	
    	public string MealPreference { get; set; }
    	
    	public string Allergies { get; set; }
    	
    	public Nullable<System.TimeSpan> MealTime { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    	
    	public Nullable<int> ChangedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public Student Student { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    		
    		
        
    		public User User1 { get; set; }
    	
    	}
}
