//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class User : BaseClass
    {
        public User()
        {
            this.Activity = new HashSet<Activity>();
    		
            this.Application = new HashSet<Application>();
    		
            this.Asset = new HashSet<Asset>();
    		
            this.Asset1 = new HashSet<Asset>();
    		
            this.Attendance = new HashSet<Attendance>();
    		
            this.Attendance1 = new HashSet<Attendance>();
    		
            this.Audit = new HashSet<Audit>();
    		
            this.Biometric = new HashSet<Biometric>();
    		
            this.Biometric1 = new HashSet<Biometric>();
    		
            this.Consumable = new HashSet<Consumable>();
    		
            this.Consumable1 = new HashSet<Consumable>();
    		
            this.HitecJob = new HashSet<HitecJob>();
    		
            this.HitecJob1 = new HashSet<HitecJob>();
    		
            this.Organization = new HashSet<Organization>();
    		
            this.Page = new HashSet<Page>();
    		
            this.Part = new HashSet<Part>();
    		
            this.Person = new HashSet<Person>();
    		
            this.Person1 = new HashSet<Person>();
    		
            this.StockTake = new HashSet<StockTake>();
    		
            this.Student = new HashSet<Student>();
    		
            this.Student1 = new HashSet<Student>();
    		
            this.StudentMeal = new HashSet<StudentMeal>();
    		
            this.StudentMeal1 = new HashSet<StudentMeal>();
    		
            this.User1 = new HashSet<User>();
    		
            this.User11 = new HashSet<User>();
    		
            this.User12 = new HashSet<User>();
    		
            this.UserRoleActivity = new HashSet<UserRoleActivity>();
    		
            this.UserRoleNotificationLevel = new HashSet<UserRoleNotificationLevel>();
    		
            this.WorkOrder = new HashSet<WorkOrder>();
    		
            this.WorkOrder1 = new HashSet<WorkOrder>();
    		
            this.WorkOrderPart = new HashSet<WorkOrderPart>();
    		
        }
    
        // Primitive properties
    
    	
    	public int UserID { get; set; }
    	
    	public Nullable<int> ContactID { get; set; }
    	
    	public string UserName { get; set; }
    	
    	public string FullName { get; set; }
    	
    	public string UserPWD { get; set; }
    	
    	public string UserPWDHash { get; set; }
    	
    	public string ConfirmPassword { get; set; }
    	
    	public string Email { get; set; }
    	
    	public bool Registered { get; set; }
    	
    	public int UserRoleID { get; set; }
    	
    	public Nullable<int> SupervisorID { get; set; }
    	
    	public Nullable<int> StpLanguageID { get; set; }
    	
    	public Nullable<int> StpThemeID { get; set; }
    	
    	public Nullable<int> StpDepartmentID { get; set; }
    	
    	public bool IsReset { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    	
    	public Nullable<int> ChangedByID { get; set; }
    
    		// Navigation properties
    
    	    
    	
    		public ICollection<Activity> Activity { get; set; }
    	
    	    
    	
    		public ICollection<Application> Application { get; set; }
    	
    	    
    	
    		public ICollection<Asset> Asset { get; set; }
    	
    	    
    	
    		public ICollection<Asset> Asset1 { get; set; }
    	
    	    
    	
    		public ICollection<Attendance> Attendance { get; set; }
    	
    	    
    	
    		public ICollection<Attendance> Attendance1 { get; set; }
    	
    	    
    	
    		public ICollection<Audit> Audit { get; set; }
    	
    	    
    	
    		public ICollection<Biometric> Biometric { get; set; }
    	
    	    
    	
    		public ICollection<Biometric> Biometric1 { get; set; }
    	
    	    
    	
    		public ICollection<Consumable> Consumable { get; set; }
    	
    	    
    	
    		public ICollection<Consumable> Consumable1 { get; set; }
    	
    		
    		
        
    		public Contact Contact { get; set; }
    	
    	    
    	
    		public ICollection<HitecJob> HitecJob { get; set; }
    	
    	    
    	
    		public ICollection<HitecJob> HitecJob1 { get; set; }
    	
    	    
    	
    		public ICollection<Organization> Organization { get; set; }
    	
    		
    		
        
    		public Organization Organization1 { get; set; }
    	
    	    
    	
    		public ICollection<Page> Page { get; set; }
    	
    	    
    	
    		public ICollection<Part> Part { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person1 { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    	    
    	
    		public ICollection<StockTake> StockTake { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public StpData StpData1 { get; set; }
    	
    		
    		
        
    		public StpData StpData2 { get; set; }
    	
    	    
    	
    		public ICollection<Student> Student { get; set; }
    	
    	    
    	
    		public ICollection<Student> Student1 { get; set; }
    	
    	    
    	
    		public ICollection<StudentMeal> StudentMeal { get; set; }
    	
    	    
    	
    		public ICollection<StudentMeal> StudentMeal1 { get; set; }
    	
    	    
    	
    		public ICollection<User> User1 { get; set; }
    	
    		
    		
        
    		public User User2 { get; set; }
    	
    	    
    	
    		public ICollection<User> User11 { get; set; }
    	
    		
    		
        
    		public User User3 { get; set; }
    	
    	    
    	
    		public ICollection<User> User12 { get; set; }
    	
    		
    		
        
    		public User User4 { get; set; }
    	
    		
    		
        
    		public UserRole UserRole { get; set; }
    	
    	    
    	
    		public ICollection<UserRoleActivity> UserRoleActivity { get; set; }
    	
    	    
    	
    		public ICollection<UserRoleNotificationLevel> UserRoleNotificationLevel { get; set; }
    	
    	    
    	
    		public ICollection<WorkOrder> WorkOrder { get; set; }
    	
    	    
    	
    		public ICollection<WorkOrder> WorkOrder1 { get; set; }
    	
    	    
    	
    		public ICollection<WorkOrderPart> WorkOrderPart { get; set; }
    	
    	}
}
