//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class UserRoleNotificationLevel : BaseClass
    {
        // Primitive properties
    
    	
    	public int UserRoleNotificationLevelID { get; set; }
    	
    	public Nullable<int> UserRoleActivityID { get; set; }
    	
    	public Nullable<int> NotificationLevelID { get; set; }
    	
    	public Nullable<int> StpUserActionID { get; set; }
    	
    	public Nullable<int> StpPendingStatusID { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public NotificationLevel NotificationLevel { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public StpData StpData1 { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    		
    		
        
    		public UserRoleActivity UserRoleActivity { get; set; }
    	
    	}
}
