//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class UserRoleActivity : BaseClass
    {
        public UserRoleActivity()
        {
            this.UserRoleNotificationLevel = new HashSet<UserRoleNotificationLevel>();
    		
        }
    
        // Primitive properties
    
    	
    	public int UserRoleActivityID { get; set; }
    	
    	public int UserRoleID { get; set; }
    	
    	public int ActivityID { get; set; }
    	
    	public Nullable<int> StcPermissionID { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Activity Activity { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    		
    		
        
    		public StcData StcData1 { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    		
    		
        
    		public UserRole UserRole { get; set; }
    	
    	    
    	
    		public ICollection<UserRoleNotificationLevel> UserRoleNotificationLevel { get; set; }
    	
    	}
}
