//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class UserRole : BaseClass
    {
        public UserRole()
        {
            this.User = new HashSet<User>();
    		
            this.UserRoleActivity = new HashSet<UserRoleActivity>();
    		
        }
    
        // Primitive properties
    
    	
    	public int UserRoleID { get; set; }
    	
    	public string RoleName { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public StcData StcData { get; set; }
    	
    	    
    	
    		public ICollection<User> User { get; set; }
    	
    	    
    	
    		public ICollection<UserRoleActivity> UserRoleActivity { get; set; }
    	
    	}
}
