//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class User : BaseClass
    {
        public User()
        {
            this.Activity = new HashSet<Activity>();
    		
            this.Application = new HashSet<Application>();
    		
            this.Asset = new HashSet<Asset>();
    		
            this.Asset1 = new HashSet<Asset>();
    		
            this.Audit = new HashSet<Audit>();
    		
            this.Consumable = new HashSet<Consumable>();
    		
            this.Consumable1 = new HashSet<Consumable>();
    		
            this.Document = new HashSet<Document>();
    		
            this.Document1 = new HashSet<Document>();
    		
            this.Message = new HashSet<Message>();
    		
            this.Message1 = new HashSet<Message>();
    		
            this.MessageUser = new HashSet<MessageUser>();
    		
            this.Organization = new HashSet<Organization>();
    		
            this.Page = new HashSet<Page>();
    		
            this.Person = new HashSet<Person>();
    		
            this.Person1 = new HashSet<Person>();
    		
            this.Person2 = new HashSet<Person>();
    		
            this.Product = new HashSet<Product>();
    		
            this.Product1 = new HashSet<Product>();
    		
            this.Production = new HashSet<Production>();
    		
            this.Production1 = new HashSet<Production>();
    		
            this.Production2 = new HashSet<Production>();
    		
            this.Supplier = new HashSet<Supplier>();
    		
            this.Supplier1 = new HashSet<Supplier>();
    		
            this.Supplier2 = new HashSet<Supplier>();
    		
            this.User1 = new HashSet<User>();
    		
            this.User11 = new HashSet<User>();
    		
            this.User12 = new HashSet<User>();
    		
            this.UserRoleActivity = new HashSet<UserRoleActivity>();
    		
            this.UserRoleNotificationLevel = new HashSet<UserRoleNotificationLevel>();
    		
        }
    
        // Primitive properties
    
    	
    	public int UserID { get; set; }
    	
    	public Nullable<int> ContactID { get; set; }
    	
    	public string UserName { get; set; }
    	
    	public string Firstname { get; set; }
    	
    	public string Surname { get; set; }
    	
    	public string UserPWD { get; set; }
    	
    	public string UserPWDHash { get; set; }
    	
    	public string ConfirmPassword { get; set; }
    	
    	public string Email { get; set; }
    	
    	public bool Registered { get; set; }
    	
    	public int UserRoleID { get; set; }
    	
    	public Nullable<int> SupervisorID { get; set; }
    	
    	public Nullable<int> StpLanguageID { get; set; }
    	
    	public Nullable<int> StpThemeID { get; set; }
    	
    	public Nullable<int> StpDepartmentID { get; set; }
    	
    	public byte[] Photo { get; set; }
    	
    	public bool IsReset { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    	
    	public Nullable<int> ChangedByID { get; set; }
    
    		// Navigation properties
    
    	    
    	
    		public ICollection<Activity> Activity { get; set; }
    	
    	    
    	
    		public ICollection<Application> Application { get; set; }
    	
    	    
    	
    		public ICollection<Asset> Asset { get; set; }
    	
    	    
    	
    		public ICollection<Asset> Asset1 { get; set; }
    	
    	    
    	
    		public ICollection<Audit> Audit { get; set; }
    	
    	    
    	
    		public ICollection<Consumable> Consumable { get; set; }
    	
    	    
    	
    		public ICollection<Consumable> Consumable1 { get; set; }
    	
    		
    		
        
    		public Contact Contact { get; set; }
    	
    	    
    	
    		public ICollection<Document> Document { get; set; }
    	
    	    
    	
    		public ICollection<Document> Document1 { get; set; }
    	
    	    
    	
    		public ICollection<Message> Message { get; set; }
    	
    	    
    	
    		public ICollection<Message> Message1 { get; set; }
    	
    	    
    	
    		public ICollection<MessageUser> MessageUser { get; set; }
    	
    	    
    	
    		public ICollection<Organization> Organization { get; set; }
    	
    		
    		
        
    		public Organization Organization1 { get; set; }
    	
    	    
    	
    		public ICollection<Page> Page { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person1 { get; set; }
    	
    	    
    	
    		public ICollection<Person> Person2 { get; set; }
    	
    	    
    	
    		public ICollection<Product> Product { get; set; }
    	
    	    
    	
    		public ICollection<Product> Product1 { get; set; }
    	
    	    
    	
    		public ICollection<Production> Production { get; set; }
    	
    	    
    	
    		public ICollection<Production> Production1 { get; set; }
    	
    	    
    	
    		public ICollection<Production> Production2 { get; set; }
    	
    		
    		
        
    		public StcData StcData { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public StpData StpData1 { get; set; }
    	
    		
    		
        
    		public StpData StpData2 { get; set; }
    	
    	    
    	
    		public ICollection<Supplier> Supplier { get; set; }
    	
    	    
    	
    		public ICollection<Supplier> Supplier1 { get; set; }
    	
    	    
    	
    		public ICollection<Supplier> Supplier2 { get; set; }
    	
    	    
    	
    		public ICollection<User> User1 { get; set; }
    	
    		
    		
        
    		public User User2 { get; set; }
    	
    	    
    	
    		public ICollection<User> User11 { get; set; }
    	
    		
    		
        
    		public User User3 { get; set; }
    	
    	    
    	
    		public ICollection<User> User12 { get; set; }
    	
    		
    		
        
    		public User User4 { get; set; }
    	
    		
    		
        
    		public UserRole UserRole { get; set; }
    	
    	    
    	
    		public ICollection<UserRoleActivity> UserRoleActivity { get; set; }
    	
    	    
    	
    		public ICollection<UserRoleNotificationLevel> UserRoleNotificationLevel { get; set; }
    	
    	}
}
