//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class vwStockReport : BaseClass
    {
        // Primitive properties
    
    	
    	public int CountQuantity { get; set; }
    	
    	public Nullable<int> AvailableQuantity { get; set; }
    	
    	public string Location { get; set; }
    	
    	public System.DateTime StockTakeDate { get; set; }
    	
    	public string CreatedBy { get; set; }
    	
    	public int Partid { get; set; }
    	
    	public string Code { get; set; }
    	
    	public string Description { get; set; }
    	
    	public string Model { get; set; }
    	
    	public string SerialNo { get; set; }
    	
    	public string UnitOfMeasure { get; set; }
    	
    	public Nullable<decimal> Price { get; set; }
    	
    	public Nullable<long> RowNumber { get; set; }
    	
    	public Nullable<int> TotalRows { get; set; }
    
    }
}
