//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    
    public partial class WorkOrder : BaseClass
    {
        public WorkOrder()
        {
            this.WorkOrderPart = new HashSet<WorkOrderPart>();
    		
        }
    
        // Primitive properties
    
    	
    	public int WorkOrderID { get; set; }
    	
    	public string WorkOrderCode { get; set; }
    	
    	public string Description { get; set; }
    	
    	public int StpWorkOrderTypeID { get; set; }
    	
    	public int TechnicianID { get; set; }
    	
    	public Nullable<int> StpClientID { get; set; }
    	
    	public string ClientContact { get; set; }
    	
    	public string ClientPhone { get; set; }
    	
    	public string Address { get; set; }
    	
    	public Nullable<System.DateTime> ScheduledDate { get; set; }
    	
    	public Nullable<System.TimeSpan> StartTime { get; set; }
    	
    	public Nullable<System.TimeSpan> EndTime { get; set; }
    	
    	public Nullable<System.DateTime> CompletedDate { get; set; }
    	
    	public string WorkedHours { get; set; }
    	
    	public Nullable<System.TimeSpan> TravelTime { get; set; }
    	
    	public bool IsQuote { get; set; }
    	
    	public Nullable<System.DateTime> QuoteAcceptedDate { get; set; }
    	
    	public string QuoteAcceptedBy { get; set; }
    	
    	public Nullable<int> CreatedByID { get; set; }
    
    		// Navigation properties
    
    		
    		
        
    		public Organization Organization { get; set; }
    	
    		
    		
        
    		public StpData StpData { get; set; }
    	
    		
    		
        
    		public StpData StpData1 { get; set; }
    	
    		
    		
        
    		public User User { get; set; }
    	
    		
    		
        
    		public User User1 { get; set; }
    	
    	    
    	
    		public ICollection<WorkOrderPart> WorkOrderPart { get; set; }
    	
    	}
}
